### ISSUE TITLE
NullPointerException when restoring from checkpoint

### ISSUE THREAD

**Issue by jamiedoornbos** [sutugin/spark-streaming-jdbc-source#2]
Hi, thanks a lot for writing this library.

I'm currently trying to set up JDBC streaming in Databricks. The source code is in pyspark, but it gets translated to java/scala in the usual way. The code works the first time through. I can see streaming activity. I can see the files in my S3 `_checkpoints` directory, which I provide in the `checkpointLocation` parameter. I can also see my test data in the target delta table.

But if I stop and re-run, it fails, apparently while loading the checkpoint data. It happens whether or not I restart the cluster. The stack trace shows that there is a `JDBCOffset` object with a `null` value for offset. I'm new to this so could easily be doing something wrong. But the code is not too complicated, maybe there's a problem with checkpoints.

The failing line of code is [this one](https://github.com/sutugin/spark-streaming-jdbc-source/blob/master/src/main/scala/org/apache/spark/sql/execution/streaming/sources/offset/JDBCOffset.scala#L27).

Code snippet:
```
# this is referencing some things I have defined from my environment, but is all working the 1st time through
jdbcOptions = {
    "user": source.admin_row.user,
    "password": env.secret('db.{}'.format(source.name())),
    "database": source.admin_row.database,
    "driver": 'org.mariadb.jdbc.Driver',
    "url": 'jdbc:mysql://%s:3306/%s' % (source.admin_row.host, source.admin_row.database)
}

jdbcOptions["dbtable"] = "streaming_test"
jdbcOptions["offsetColumn"] = "date_created"

stream = spark.readStream.format("jdbc-streaming")
# there is no options method in pyspark, so add each option individually
for name, value in jdbcOptions.items():
    stream = stream.option(name, value)
stream = stream.load()

table_name = 'streaming_test'
( stream.writeStream
    .format("delta")
    .outputMode("append")
    .option("checkpointLocation", "{}/extract/_checkpoints/{}".format(env.other_root, table_name))
    .start(env.location(table_name)) )
```

Stack trace:
```
java.lang.NullPointerException
	at org.apache.spark.sql.execution.streaming.sources.offset.JDBCOffset.toString(JDBCOffset.scala:27)
	at java.lang.String.valueOf(String.java:2994)
	at scala.collection.mutable.StringBuilder.append(StringBuilder.scala:200)
	at scala.collection.TraversableOnce$$anonfun$addString$1.apply(TraversableOnce.scala:359)
	at scala.collection.Iterator$class.foreach(Iterator.scala:891)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1334)
	at scala.collection.TraversableOnce$class.addString(TraversableOnce.scala:357)
	at scala.collection.AbstractIterator.addString(Iterator.scala:1334)
	at scala.collection.TraversableOnce$class.mkString(TraversableOnce.scala:323)
	at scala.collection.AbstractIterator.mkString(Iterator.scala:1334)
	at scala.runtime.ScalaRunTime$._toString(ScalaRunTime.scala:166)
	at scala.Some.toString(Option.scala:333)
	at java.lang.String.valueOf(String.java:2994)
	at java.lang.StringBuilder.append(StringBuilder.java:131)
	at scala.StringContext.standardInterpolator(StringContext.scala:125)
	at scala.StringContext.s(StringContext.scala:95)
	at org.apache.spark.sql.execution.streaming.sources.JDBCStreamSource$$anonfun$getBatch$3.apply(JDBCStreamSource.scala:136)
	at org.apache.spark.sql.execution.streaming.sources.JDBCStreamSource$$anonfun$getBatch$3.apply(JDBCStreamSource.scala:136)
	at org.apache.spark.internal.Logging$class.logInfo(Logging.scala:54)
	at org.apache.spark.sql.execution.streaming.sources.JDBCStreamSource.logInfo(JDBCStreamSource.scala:15)
	at org.apache.spark.sql.execution.streaming.sources.JDBCStreamSource.getBatch(JDBCStreamSource.scala:136)
	at org.apache.spark.sql.execution.streaming.MicroBatchExecution$$anonfun$org$apache$spark$sql$execution$streaming$MicroBatchExecution$$populateStartOffsets$2.apply(MicroBatchExecution.scala:295)
	at org.apache.spark.sql.execution.streaming.MicroBatchExecution$$anonfun$org$apache$spark$sql$execution$streaming$MicroBatchExecution$$populateStartOffsets$2.apply(MicroBatchExecution.scala:292)
	at scala.collection.Iterator$class.foreach(Iterator.scala:891)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1334)
	at scala.collection.IterableLike$class.foreach(IterableLike.scala:72)
	at org.apache.spark.sql.execution.streaming.StreamProgress.foreach(StreamProgress.scala:25)
	at org.apache.spark.sql.execution.streaming.MicroBatchExecution.org$apache$spark$sql$execution$streaming$MicroBatchExecution$$populateStartOffsets(MicroBatchExecution.scala:292)
	at org.apache.spark.sql.execution.streaming.MicroBatchExecution$$anonfun$runActivatedStream$1$$anonfun$apply$mcZ$sp$1.apply$mcV$sp(MicroBatchExecution.scala:179)
	at org.apache.spark.sql.execution.streaming.MicroBatchExecution$$anonfun$runActivatedStream$1$$anonfun$apply$mcZ$sp$1.apply(MicroBatchExecution.scala:176)
	at org.apache.spark.sql.execution.streaming.MicroBatchExecution$$anonfun$runActivatedStream$1$$anonfun$apply$mcZ$sp$1.apply(MicroBatchExecution.scala:176)
	at org.apache.spark.sql.execution.streaming.ProgressReporter$class.reportTimeTaken(ProgressReporter.scala:263)
	at org.apache.spark.sql.execution.streaming.StreamExecution.reportTimeTaken(StreamExecution.scala:61)
	at org.apache.spark.sql.execution.streaming.MicroBatchExecution$$anonfun$runActivatedStream$1.apply$mcZ$sp(MicroBatchExecution.scala:176)
	at org.apache.spark.sql.execution.streaming.ProcessingTimeExecutor.execute(TriggerExecutor.scala:56)
	at org.apache.spark.sql.execution.streaming.MicroBatchExecution.runActivatedStream(MicroBatchExecution.scala:170)
	at org.apache.spark.sql.execution.streaming.StreamExecution.org$apache$spark$sql$execution$streaming$StreamExecution$$runStream(StreamExecution.scala:296)
	at org.apache.spark.sql.execution.streaming.StreamExecution$$anon$1.run(StreamExecution.scala:208)
```

Is there anything else I can provide? The target database is MySQL and the `date_created` column is type `datetime`. This kind of column works fine for me normally and shows up as a python `datetime` object. It presumably has the appropriate java type under the hood, but I haven't checked that.

In the commits folder under the checkpoint location, I see a single "0" file, the contents don't look right, so maybe it's a result of the previous run not writing out the right data. Here is the content:
```
v1
{"nextBatchWatermarkMs":0}
```

**Comment by sutugin** [comment]
Thank you, @jamiedoornbos, yesterday I made changes and did not have time to test everything, the error is fixed, you can check.

**Comment by jamiedoornbos** [comment]
Thank you, this is totally working for me now!
