### ISSUE TITLE
If there is no record in the table, the program will crash when jdbc-source Query is started

### ISSUE THREAD

**Issue by roychen11232357** [sutugin/spark-streaming-jdbc-source#4]
Hi, sutugin
 First of all, thank you for sharing such a cool thing! There are so few resources about jdbc streaming for spark!
 
 I found an issue, If there is no record in the table, the program will crash when jdbc-source Query is started,
But if there is data already existed in the table, then it runs fine!

the error message below
```
21/04/09 15:37:27 WARN JDBCStreamSource: Not found offset scala.collection.Iterator$$anon$2.next(Iterator.scala:41)
scala.collection.Iterator$$anon$2.next(Iterator.scala:39)
scala.collection.IndexedSeqLike$Elements.next(IndexedSeqLike.scala:63)
scala.collection.IterableLike.head(IterableLike.scala:109)
scala.collection.IterableLike.head$(IterableLike.scala:108)
scala.collection.mutable.ArrayOps$ofRef.scala$collection$IndexedSeqOptimized$$super$head(ArrayOps.scala:198)
scala.collection.IndexedSeqOptimized.head(IndexedSeqOptimized.scala:129)
scala.collection.IndexedSeqOptimized.head$(IndexedSeqOptimized.scala:129)
scala.collection.mutable.ArrayOps$ofRef.head(ArrayOps.scala:198)
org.apache.spark.sql.Dataset.head(Dataset.scala:2729)
org.apache.spark.sql.Dataset.first(Dataset.scala:2736)
org.apache.spark.sql.execution.streaming.sources.JDBCStreamSource.$anonfun$getOffsetValue$1(JDBCStreamSource.scala:36)
scala.util.Try$.apply(Try.scala:213)
org.apache.spark.sql.execution.streaming.sources.JDBCStreamSource.getOffsetValue(JDBCStreamSource.scala:36)
org.apache.spark.sql.execution.streaming.sources.JDBCStreamSource.initFirstOffset(JDBCStreamSource.scala:44)
org.apache.spark.sql.execution.streaming.sources.JDBCStreamSource.getOffset(JDBCStreamSource.scala:135)
org.apache.spark.sql.execution.streaming.MicroBatchExecution.$anonfun$constructNextBatch$6(MicroBatchExecution.scala:399)
org.apache.spark.sql.execution.streaming.ProgressReporter.reportTimeTaken(ProgressReporter.scala:357)
org.apache.spark.sql.execution.streaming.ProgressReporter.reportTimeTaken$(ProgressReporter.scala:355)
org.apache.spark.sql.execution.streaming.StreamExecution.reportTimeTaken(StreamExecution.scala:68)
org.apache.spark.sql.execution.streaming.MicroBatchExecution.$anonfun$constructNextBatch$2(MicroBatchExecution.scala:399)
scala.collection.TraversableLike.$anonfun$map$1(TraversableLike.scala:238)
scala.collection.immutable.Map$Map1.foreach(Map.scala:128)
scala.collection.TraversableLike.map(TraversableLike.scala:238)
scala.collection.TraversableLike.map$(TraversableLike.scala:231)
scala.collection.AbstractTraversable.map(Traversable.scala:108)
org.apache.spark.sql.execution.streaming.MicroBatchExecution.$anonfun$constructNextBatch$1(MicroBatchExecution.scala:382)
scala.runtime.java8.JFunction0$mcZ$sp.apply(JFunction0$mcZ$sp.java:23)
org.apache.spark.sql.execution.streaming.MicroBatchExecution.withProgressLocked(MicroBatchExecution.scala:613)
org.apache.spark.sql.execution.streaming.MicroBatchExecution.constructNextBatch(MicroBatchExecution.scala:378)
org.apache.spark.sql.execution.streaming.MicroBatchExecution.$anonfun$runActivatedStream$2(MicroBatchExecution.scala:211)
scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
org.apache.spark.sql.execution.streaming.ProgressReporter.reportTimeTaken(ProgressReporter.scala:357)
org.apache.spark.sql.execution.streaming.ProgressReporter.reportTimeTaken$(ProgressReporter.scala:355)
org.apache.spark.sql.execution.streaming.StreamExecution.reportTimeTaken(StreamExecution.scala:68)
org.apache.spark.sql.execution.streaming.MicroBatchExecution.$anonfun$runActivatedStream$1(MicroBatchExecution.scala:194)
org.apache.spark.sql.execution.streaming.ProcessingTimeExecutor.execute(TriggerExecutor.scala:57)
org.apache.spark.sql.execution.streaming.MicroBatchExecution.runActivatedStream(MicroBatchExecution.scala:188)
org.apache.spark.sql.execution.streaming.StreamExecution.org$apache$spark$sql$execution$streaming$StreamExecution$$runStream(StreamExecution.scala:333)
org.apache.spark.sql.execution.streaming.StreamExecution$$anon$1.run(StreamExecution.scala:244)
21/04/09 15:37:27 ERROR MicroBatchExecution: Query [id = ad0f663f-94ec-4eb9-bc1d-6b19925a7693, runId = 39222379-a93f-4b19-a5e8-e248434a9674] terminated with error
java.util.NoSuchElementException: None.get
	at scala.None$.get(Option.scala:529)
	at scala.None$.get(Option.scala:527)
	at org.apache.spark.sql.execution.streaming.sources.JDBCStreamSource.initFirstOffset(JDBCStreamSource.scala:44)
	at org.apache.spark.sql.execution.streaming.sources.JDBCStreamSource.getOffset(JDBCStreamSource.scala:135)
	at org.apache.spark.sql.execution.streaming.MicroBatchExecution.$anonfun$constructNextBatch$6(MicroBatchExecution.scala:399)
	at org.apache.spark.sql.execution.streaming.ProgressReporter.reportTimeTaken(ProgressReporter.scala:357)
	at org.apache.spark.sql.execution.streaming.ProgressReporter.reportTimeTaken$(ProgressReporter.scala:355)
	at org.apache.spark.sql.execution.streaming.StreamExecution.reportTimeTaken(StreamExecution.scala:68)
	at org.apache.spark.sql.execution.streaming.MicroBatchExecution.$anonfun$constructNextBatch$2(MicroBatchExecution.scala:399)
	at scala.collection.TraversableLike.$anonfun$map$1(TraversableLike.scala:238)
	at scala.collection.immutable.Map$Map1.foreach(Map.scala:128)
	at scala.collection.TraversableLike.map(TraversableLike.scala:238)
	at scala.collection.TraversableLike.map$(TraversableLike.scala:231)
	at scala.collection.AbstractTraversable.map(Traversable.scala:108)
	at org.apache.spark.sql.execution.streaming.MicroBatchExecution.$anonfun$constructNextBatch$1(MicroBatchExecution.scala:382)
	at scala.runtime.java8.JFunction0$mcZ$sp.apply(JFunction0$mcZ$sp.java:23)
	at org.apache.spark.sql.execution.streaming.MicroBatchExecution.withProgressLocked(MicroBatchExecution.scala:613)
	at org.apache.spark.sql.execution.streaming.MicroBatchExecution.constructNextBatch(MicroBatchExecution.scala:378)
	at org.apache.spark.sql.execution.streaming.MicroBatchExecution.$anonfun$runActivatedStream$2(MicroBatchExecution.scala:211)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
	at org.apache.spark.sql.execution.streaming.ProgressReporter.reportTimeTaken(ProgressReporter.scala:357)
	at org.apache.spark.sql.execution.streaming.ProgressReporter.reportTimeTaken$(ProgressReporter.scala:355)
	at org.apache.spark.sql.execution.streaming.StreamExecution.reportTimeTaken(StreamExecution.scala:68)
	at org.apache.spark.sql.execution.streaming.MicroBatchExecution.$anonfun$runActivatedStream$1(MicroBatchExecution.scala:194)
	at org.apache.spark.sql.execution.streaming.ProcessingTimeExecutor.execute(TriggerExecutor.scala:57)
	at org.apache.spark.sql.execution.streaming.MicroBatchExecution.runActivatedStream(MicroBatchExecution.scala:188)
	at org.apache.spark.sql.execution.streaming.StreamExecution.org$apache$spark$sql$execution$streaming$StreamExecution$$runStream(StreamExecution.scala:333)
	at org.apache.spark.sql.execution.streaming.StreamExecution$$anon$1.run(StreamExecution.scala:244)
21/04/09 15:37:27 WARN JDBCStreamSource: Stop is not implemented!

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/dev/work/spark-3.1.1-bin-hadoop2.7/python/pyspark/sql/streaming.py", line 101, in awaitTermination
    return self._jsq.awaitTermination()
  File "/home/dev/work/spark-3.1.1-bin-hadoop2.7/python/lib/py4j-0.10.9-src.zip/py4j/java_gateway.py", line 1305, in __call__
  File "/home/dev/work/spark-3.1.1-bin-hadoop2.7/python/pyspark/sql/utils.py", line 117, in deco
    raise converted from None
pyspark.sql.utils.StreamingQueryException: None.get
=== Streaming Query ===
Identifier: [id = ad0f663f-94ec-4eb9-bc1d-6b19925a7693, runId = 39222379-a93f-4b19-a5e8-e248434a9674]
Current Committed Offsets: {}
Current Available Offsets: {}

Current State: ACTIVE
Thread State: RUNNABLE

Logical Plan:
WriteToMicroBatchDataSource ConsoleWriter[numRows=20, truncate=true]
+- StreamingExecutionRelation org.apache.spark.sql.execution.streaming.sources.JDBCStreamSource@2083307e, [value#6, ts#7]

```

BTW, I use pyspark for testing, Below is my python code
```
spark = (SparkSession
.builder
.appName("jdbc")
.master('local[2]')
.config("spark.jars", ",".join(jars))
.getOrCreate())
stream = spark.readStream.format("jdbc-streaming").options(url='jdbc:postgresql://127.0.0.1:5432/postgres',
dbtable='public.test',
driver='org.postgresql.Driver',
user='postgres',
password='mysecretpassword',
offsetColumn='ts',
startingoffset='latest').load()

query = stream.writeStream.outputMode("append").format("console").start()

query.awaitTermination()
```

Please help confirm whether it is a bug, Thanks so much!

**Comment by sutugin** [comment]
Hi, @roychen11232357! 
Yes, there was such a problem, I fixed it, you can check, there will be questions or problems-write
